name: WebView
options:
  bundleIdPrefix: com.youtube.webview
targets:
  WebView:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [WebView]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_NAME: "YouTube"  # Telefonda uygulamanın simgesinin altında yazacak isim
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
