name: WebView
options:
  bundleIdPrefix: com.haxbey
targets:
  WebView:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [WebView]
    settings:
      GENERATE_INFOPLIST_FILE: YES
