name: iOS App Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4
        
      - name: Xcode'u Ayarla
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: XcodeGen Kur
        run: brew install xcodegen
        
      - name: xcodeproj Dosyasını Otomatik Üret
        run: xcodegen generate
          
      - name: Projeyi Derle (İmzasız Gerçek Cihaz Çıktısı)
        run: |
          xcodebuild clean build \
            -project WebView.xcodeproj \
            -scheme WebView \
            -configuration Release \
            -sdk iphoneos \
            SYMROOT=$(PWD)/build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: IPA Dosyasını Paketle
        run: |
          mkdir -p Payload
          mv build/Release-iphoneos/YouTube.app Payload/
          zip -r YouTube-App.ipa Payload
          
      - name: IPA'yı İndirme Linki Olarak Yükle
        uses: actions/upload-artifact@v4
        with:
          name: YouTube
          path: YouTube-App.ipa
